import { render, screen } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';

import RootLayout, { metadata } from './layout';

vi.mock('@/styles/index.scss', () => ({}));

describe('RootLayout & Metadata', () => {
  describe('Metadata Configuration', () => {
    it('should export correct metadata object for Next.js SEO', () => {
      expect(metadata).toBeDefined();
      expect(metadata.title).toBe('Swagger Editor App');
      expect(metadata.description).toBe('Generated by create next app');
    });
  });

  describe('Component Rendering', () => {
    it('should transparently render provided children', () => {
      const testText = 'Hello from Inner Page!';

      render(
        <RootLayout>
          <div data-testid="child-element">{testText}</div>
        </RootLayout>
      );

      const child = screen.getByTestId('child-element');
      expect(child).toBeInTheDocument();
      expect(child).toHaveTextContent(testText);
    });
  });
});
