import type { Metadata } from 'next';

import '@/styles/index.scss';

export const metadata: Metadata = {
  title: 'Swagger Editor App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return children;
}
